### ISSUE TITLE
Preprocessing recipe parameters save

### ISSUE THREAD

**Issue by AdrienMtgn** [dataiku/dss-plugin-tesseract-ocr#28]
Hi there,

I think there is a issue with the image-preprocessing recipe.

When I change the parameters (adding an image processing function or changing the pipeline), when I close and open the recipe, my custom code is replaced with the default code and the recipe can be save (dss recognise the recipe as changed).

For exemple, I add a print statement in the resize function :
![image](https://user-images.githubusercontent.com/29199604/106002996-0d637880-60b2-11eb-8c56-fc2849942b57.png)

When I run the recipe, the new code is used (we can see the prints in the logs)
![image](https://user-images.githubusercontent.com/29199604/106004470-8adbb880-60b3-11eb-88e9-aa7684340517.png)

But when I close and open the recipe (or if I refresh the page), the default code is back.
![image](https://user-images.githubusercontent.com/29199604/106003842-e35e8600-60b2-11eb-9237-9068360e3a94.png)

My guess is, the code part from the template should be moved from the [parameter template file](https://github.com/dataiku/dss-plugin-tesseract-ocr/blob/master/resource/image-processing-template.html) to some default values inside new parameters in the [recipe parameters file](https://github.com/dataiku/dss-plugin-tesseract-ocr/blob/master/custom-recipes/image-processing-custom/recipe.json) that would do the trick.

I'm quite busy right know so I'm going to use standart python recipe for now, but it would be nice to have this work :)

PS : using dss 8.0.1

Edit : message was not finiched...

**Comment by StanislasGuinel** [comment]
Hi,
Thanks for posting this issue, it's now in the backlog, I will let you know when it's fixed.

**Comment by StanislasGuinel** [comment]
Hi @AdrienMtgn,
We did a new release of the [plugin](https://github.com/dataiku/dss-plugin-tesseract-ocr/releases/tag/v1.0.1) that fix this issue.
